present_year = 4327

[[views]]
id = "master"
title = "World History (Truth)"
tags_none = ["private"]
tick_scale = "decade"
tick_spacing_px = 72
sort_direction = "desc"

[[views]]
id = "public"
title = "World History (Public)"
tags_all = ["public"]
tick_scale = "decade"
tick_spacing_px = 72
sort_direction = "desc"
