present_year = 4327

[[views]]
id = "master"
title = "World History (Truth)"
pov = "truth"
include_povs = ["public", "party"]
tick_scale = "decade"
tick_spacing_px = 72
sort_direction = "desc"

[[views]]
id = "public"
title = "World History (Public)"
pov = "public"
tick_scale = "decade"
tick_spacing_px = 72
sort_direction = "desc"
